"""student & landlord

Revision ID: 11049bf3daa6
Revises: fc1c018a4cb4
Create Date: 2026-01-29 12:29:03.587490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11049bf3daa6'
down_revision: Union[str, Sequence[str], None] = 'fc1c018a4cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landlords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_landlords_id'), 'landlords', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(), nullable=True),
    sa.Column('furnished', sa.Boolean(), nullable=True),
    sa.Column('smoking', sa.Boolean(), nullable=True),
    sa.Column('pets', sa.Boolean(), nullable=True),
    sa.Column('noise_level', sa.Integer(), nullable=True),
    sa.Column('max_budget', sa.Float(), nullable=True),
    sa.Column('guarantor_income', sa.Float(), nullable=True),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('study_level', sa.String(), nullable=True),
    sa.Column('passions', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.add_column('users', sa.Column('telephone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo')
    op.drop_column('users', 'telephone')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_landlords_id'), table_name='landlords')
    op.drop_table('landlords')
    # ### end Alembic commands ###
