"""users table update

Revision ID: 337c9107b7c0
Revises: 4f2f9f86a3bd
Create Date: 2026-01-30 09:36:43.349310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337c9107b7c0'
down_revision: Union[str, Sequence[str], None] = '4f2f9f86a3bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('workspace', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('pets', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('tv', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('dryer', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('ac', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('garden', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('balcony', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('listings', 'balcony')
    op.drop_column('listings', 'garden')
    op.drop_column('listings', 'ac')
    op.drop_column('listings', 'dryer')
    op.drop_column('listings', 'tv')
    op.drop_column('listings', 'pets')
    op.drop_column('listings', 'workspace')
    # ### end Alembic commands ###
