"""message

Revision ID: 4653a9cb79b0
Revises: b2c3d4e5f6a1
Create Date: 2026-02-04 11:01:41.806481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4653a9cb79b0'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.add_column('likes', sa.Column('is_like', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('workspace', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('pets', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('tv', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('dryer', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('ac', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('garden', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('balcony', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('listings', 'balcony')
    op.drop_column('listings', 'garden')
    op.drop_column('listings', 'ac')
    op.drop_column('listings', 'dryer')
    op.drop_column('listings', 'tv')
    op.drop_column('listings', 'pets')
    op.drop_column('listings', 'workspace')
    op.drop_column('likes', 'is_like')
    op.create_table('matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], name=op.f('matches_landlord_id_fkey')),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('matches_listing_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('matches_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('matches_pkey')),
    sa.UniqueConstraint('student_id', 'listing_id', name=op.f('uq_match_student_listing'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    # ### end Alembic commands ###
