"""add_amenities_columns

Revision ID: 4f67e28da976
Revises: d16e7d855a50
Create Date: 2026-01-29 16:49:55.588194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f67e28da976'
down_revision: Union[str, Sequence[str], None] = 'd16e7d855a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_photos_id'), 'listing_photos', ['id'], unique=False)
    op.drop_index('ix_rooms_id', table_name='rooms')
    op.drop_table('rooms')
    op.add_column('listings', sa.Column('price', sa.Float(), nullable=True))  # nullable pour éviter les erreurs
    op.add_column('listings', sa.Column('charges_included', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('city', sa.String(), nullable=True))  # nullable pour éviter les erreurs
    op.add_column('listings', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('listings', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('room_type', sa.String(), nullable=True))  # nullable pour éviter les erreurs
    op.add_column('listings', sa.Column('floor', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('total_floors', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('min_duration_months', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('wifi', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('washing_machine', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('kitchen', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('parking', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('elevator', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('workspace', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('pets', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('tv', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('dryer', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('ac', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('garden', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('balcony', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('owner_id', sa.Integer(), nullable=True))  # nullable pour éviter les erreurs
    op.alter_column('listings', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('listings', 'surface',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('listings', 'deposit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('listings', 'address',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('listings', 'available_from',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_index('ix_listings_listing_id', table_name='listings')
    op.drop_constraint('listings_landlord_id_fkey', 'listings', type_='foreignkey')
    op.create_foreign_key(None, 'listings', 'users', ['owner_id'], ['id'])
    op.drop_column('listings', 'liked_by')
    op.drop_column('listings', 'photos')
    op.drop_column('listings', 'type')
    op.drop_column('listings', 'landlord_id')
    op.drop_column('listings', 'tenant_criteria')
    op.drop_column('listings', 'rent')
    op.drop_column('listings', 'updated_at')
    op.drop_column('listings', 'amenities')
    op.drop_column('listings', 'created_at')
    op.drop_column('listings', 'rooms')
    op.drop_column('listings', 'listing_id')
    op.drop_column('listings', 'charges')
    op.drop_column('listings', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('charges', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('listing_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('rooms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('amenities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('rent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('tenant_criteria', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('landlord_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('photos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('liked_by', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.create_foreign_key('listings_landlord_id_fkey', 'listings', 'users', ['landlord_id'], ['id'])
    op.create_index('ix_listings_listing_id', 'listings', ['listing_id'], unique=True)
    op.alter_column('listings', 'available_from',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('listings', 'address',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('listings', 'deposit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('listings', 'surface',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('listings', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('listings', 'owner_id')
    op.drop_column('listings', 'balcony')
    op.drop_column('listings', 'garden')
    op.drop_column('listings', 'ac')
    op.drop_column('listings', 'dryer')
    op.drop_column('listings', 'tv')
    op.drop_column('listings', 'pets')
    op.drop_column('listings', 'workspace')
    op.drop_column('listings', 'elevator')
    op.drop_column('listings', 'parking')
    op.drop_column('listings', 'kitchen')
    op.drop_column('listings', 'washing_machine')
    op.drop_column('listings', 'wifi')
    op.drop_column('listings', 'min_duration_months')
    op.drop_column('listings', 'total_floors')
    op.drop_column('listings', 'floor')
    op.drop_column('listings', 'room_type')
    op.drop_column('listings', 'longitude')
    op.drop_column('listings', 'latitude')
    op.drop_column('listings', 'postal_code')
    op.drop_column('listings', 'city')
    op.drop_column('listings', 'charges_included')
    op.drop_column('listings', 'price')
    op.create_table('rooms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('surface', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('charges_included', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deposit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('room_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('furnished', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_floors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('available_from', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('min_duration_months', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wifi', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('washing_machine', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('kitchen', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('parking', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('elevator', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='rooms_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rooms_pkey')
    )
    op.create_index('ix_rooms_id', 'rooms', ['id'], unique=False)
    op.drop_index(op.f('ix_listing_photos_id'), table_name='listing_photos')
    op.drop_table('listing_photos')
    # ### end Alembic commands ###
