"""replace name room table

Revision ID: cd6775ca0a30
Revises: 11049bf3daa6
Create Date: 2026-01-29 14:52:10.165867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6775ca0a30'
down_revision: Union[str, Sequence[str], None] = '11049bf3daa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('surface', sa.Float(), nullable=True),
    sa.Column('charges_included', sa.Boolean(), nullable=True),
    sa.Column('deposit', sa.Float(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('room_type', sa.String(), nullable=False),
    sa.Column('furnished', sa.Boolean(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('min_duration_months', sa.Integer(), nullable=True),
    sa.Column('wifi', sa.Boolean(), nullable=True),
    sa.Column('washing_machine', sa.Boolean(), nullable=True),
    sa.Column('kitchen', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('elevator', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('surface', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('charges_included', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deposit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('room_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('furnished', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_floors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('available_from', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('min_duration_months', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wifi', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('washing_machine', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('kitchen', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('parking', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('elevator', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('rooms_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rooms_pkey'))
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
